apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hail-ci-deployment
spec:
  selector:
    matchLabels:
      app: hail-ci
  replicas: 1
  template:
    metadata:
      labels:
        app: hail-ci
    spec:
      containers:
        - name: hail-ci
          image: gcr.io/broad-ctsa/hail-ci:b5040f34e01cb25ad1bcce4a69f4f967f7297e5d
          env:
            - name: SELF_HOSTNAME
              value: http://hail-ci
            - name: BATCH_SERVER_URL
              value: http://batch
            - name: WATCHED_TARGETS
              value: '[["hail-is/hail:master", false], ["hail-is/hail:0.1", false], ["hail-is/batch:master", false]]'
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /hail-ci/oauth-token
              readOnly: true
              name: hail-ci-0-1-github-oauth-token
            - mountPath: /hail-ci/gcloud-token
              readOnly: true
              name: hail-ci-0-1-service-account-key
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            # failure if CI is busy for > 120 seconds
            failureThreshold: 12
      volumes:
        - name: hail-ci-0-1-service-account-key
          secret:
            secretName: hail-ci-0-1-service-account-key
        - name: hail-ci-0-1-github-oauth-token
          secret:
            secretName: hail-ci-0-1-github-oauth-token
---
apiVersion: v1
kind: Service
metadata:
  name: hail-ci
  labels:
    app: hail-ci
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: hail-ci
  type: LoadBalancer
